CREATE DATABASE IF NOT EXISTS APP;
USE APP;

CREATE TABLE IF NOT EXISTS USERS (
    userId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR (256) NOT NULL,
    name VARCHAR (256) NOT NULL,
	email VARCHAR (256) NOT NULL,
	password  VARCHAR(256) NOT NULL 
);

CREATE TABLE IF NOT EXISTS MESSAGES (
    idMex INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    message TEXT(256),
    date DATE,
    userId INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES USERS (UserId)
);

